### ISSUE TITLE
Test with strict Symfony version in GitHub workflows

### ISSUE THREAD

**Issue by vincentchalamon** [silverbackis/ApiComponentBundle#25]
This bundle should follow Symfony supported versions: 3.4 (LTS), 4.4 (LTS) and 5.0 (latest).

- [x] Update composer.json require dependencies to support those versions
- [x] Update .github/workflows/ci.yml to configure `extra.symfony.require` version and test for each supported version (using matrix)

**Comment by silverbackdan** [comment]
Thank you, and yes please. We can adapt the CI to test for 4.4 and >=5.0 but no need for 3.4.

**Comment by vincentchalamon** [comment]
Example here: https://github.com/GregoireHebert/docusign-bundle/blob/71c4a12957776716182fa1b5cbd1c585e1999c43/.github/workflows/ci.yml#L72-L75
